---

on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: frederickw082922/RHEL8-CIS-Devel
      - uses: gofrolist/molecule-action@v2
